### ISSUE TITLE
Dynamic Loading Error: Win32 error 126

### ISSUE THREAD

**Issue by yegor-pelykh** [Bannerets/tdl#110]
I have such a code:

```typescript
const p = path.resolve(__dirname, './tdlib/tdjson.dll');    // Converts to correct '[project dir]\tdlib\tdjson.dll' path
const tdlib = new TDLib(p);    // throws an exception
this.client = new Client(tdlib, {
    apiId: Config.instance.apiId,
    apiHash: Config.instance.apiHash,
});
```

There are four correctly built dll files for x64 (built from sources) in directory `[project dir]\tdlib\tdjson.dll`:
libcrypto-1_1-x64.dll
libssl-1_1-x64.dll
tdjson.dll
zlib1.dll

So it should work as I have specified the overridden path to these libraries.
But it throws an exception with message `Dynamic Loading Error: Win32 error 126`

BUT!
If I copy all these files in the root folder with js files, then the client is initialized normally.

BUT AGAIN!
If I remove dll files from `[project dir]\tdlib\tdjson.dll` and keep them only in root directory, the exception is thrown again!

So it is very strange behavior.
I don't want to keep files in both the project folder and in the overridden folder.
I want to use them only from my overridden folder path.

**Comment by JesusDR01** [comment]
I found this problem too, consider following these steps: 

https://github.com/Bannerets/tdl/issues/112#issuecomment-985771264

**Comment by Bannerets** [comment]
The issue doesn't look related to #112.

The error happens because Windows can't find one of the dependencies of libtdjson. See the DLL search order on Windows: https://docs.microsoft.com/en-us/windows/win32/dlls/dynamic-link-library-search-order#standard-search-order-for-desktop-applications. tdl simply calls `LoadLibraryW("[project dir]\tdlib\tdjson.dll")`.

> If I copy all these files in the root folder with js files, then the client is initialized normally.

It probably searches for libcrypto/libssl/zlib in the root folder, and for tdjson in the path you specified (`[project dir]\tdlib\tdjson.dll`).
