### ISSUE TITLE
what's the latest supported layer?

### ISSUE THREAD

**Issue by Lucienest** [Bannerets/tdl#130]
The latest layer is 150, do u support it?
is this library automatically compatible with future layers??

**Comment by Bannerets** [comment]
- This library is merely a binding to TDLib and does not require a specific version of TDLib; to get newer Telegram features, you update TDLib (independently of tdl). So, the latest TDLib is supported.
- TDLib does not provide access to the raw Telegram API, it's more useful to speak in terms of TDLib versions rather than underlying mtproto layers.

**Comment by Lucienest** [comment]
> * This library is merely a binding to TDLib and does not require a specific version of TDLib; to get newer Telegram features, you update TDLib (independently of tdl). So, the latest TDLib is supported.
> * TDLib does not provide access to the raw Telegram API, it's more useful to speak in terms of TDLib versions rather than underlying mtproto layers.

so what about #91 
has it been implemented??

**Comment by Bannerets** [comment]
That only affects the way the library communicates with TDLib and does not change any available features.

**Comment by Lucienest** [comment]
> That only affects the way the library communicates with TDLib and does not change any available features.

is there a possibility that the current TDLib JSON interface will be deprecated in near future?
making this lib unusable with the latest version.

**Comment by Bannerets** [comment]
Then this library will be updated quickly to use the new interface, it isn't difficult.
