### ISSUE TITLE
Clients count

### ISSUE THREAD

**Issue by bubblecsh** [Bannerets/tdl#136]
> With tdl-tdlib-addon, you can create multiple clients but currently the number of created clients should not exceed [UV_THREADPOOL_SIZE]

Is there a reasonable limit of how many clients can be created per vCPU? 
Currently i have 2 vCPU's and 4 clients running great, but im wondering will it be possible to increase clients count to 20-30?

**Comment by Bannerets** [comment]
The limitation described in the quote isn't really relevant to consumed resources / vCPUs. I guess there isn't any hard limit and that heavily depends on what the clients do (there are some resource-heavy bots) and not just the number of them. You probably should try or extrapolate from the current load.

Though still do set the `UV_THREADPOOL_SIZE` env variable to a value greater than the number of clients you use simultaneously (as per the current implementation), it won't (shouldn't) work otherwise.
