### ISSUE TITLE
prebuilt-tdlib for linux-arm64

### ISSUE THREAD

**Issue by rafaeldcf** [Bannerets/tdl#161]
Is there a pre-build for linux-arm64?

I'm trying to install the project in a Raspberry but it seems that the prebuilt-tdlib doesn't have the platform:
`Error: The linux-arm64 platform is not supported`

Is there a fix for that? Building TDLib from scratch in Raspberry it's very difficult due to RAM issues.

Thanks.

**Comment by Bannerets** [comment]
Not yet. This is planned. You can use `SplitSource.php` script in the TDLib repository before building to decrease RAM requirements (see https://github.com/tdlib/td?tab=readme-ov-file#building). That should be enough for raspberry pi, although it will take a few hours to finish. (I did that a few years ago on a 1GB raspberry pi).

As a more time-consuming approach, you may also try to build it on another arm64 device. E.g., on an android phone in termux (with glibc packages). Since the openssl version will likely be different there, you probably should link it statically.

By the way, I use zram with some aggressive parameters (250% memory percent, zstd; vm.swappiness=150) on raspberry pi and that also helps with RAM issues a lot.

**Comment by Bannerets** [comment]
Added

**Comment by skygate2012** [comment]
@eilvelia Can you also add Android support?

**Comment by eilvelia** [comment]
If you mean termux on android, it should already work in [termux proot](https://wiki.termux.com/wiki/PRoot) (with glibc installed). Supporting other ways would be difficult. Probably one should package tdlib for termux and then use it in tdl (without `prebuilt-tdlib`).

**Comment by skygate2012** [comment]
Thanks using proot (with glibc) worked :)
