### ISSUE TITLE
ENOENT: no such file or directory, open 'libtdjson.so'

### ISSUE THREAD

**Issue by CristianBB** [Bannerets/tdl#51]
I have the Nodejs app working in Local.
When I tried to install it in an AWS EC2 instance with Ubuntu 18.0.4 this error appears and the app crashes.

TDLib has been succesfully build and installed in /usr/local/lib/libtdjson.so so I cannot figure what's going wrong...

The code to instanciate TDLib:

```
    tdlib = new TDLib();
    client = new Client(tdlib, {
        apiId: process.env.TELEGRAM_API_ID,
        apiHash: process.env.TELEGRAM_API_HASH
    });

    await client.connectAndLogin();
```

And the output error:

> { Error: ENOENT: no such file or directory, open 'libtdjson.so'
>     at Object.openSync (fs.js:448:3)
>     at readFileSync (fs.js:348:35)
>     at new DynamicLibrary (/home/ubuntu/teletipsters/node_modules/ffi-napi/lib/dynamic_library.js:67:23)
>     at Object.Library (/home/ubuntu/teletipsters/node_modules/ffi-napi/lib/library.js:45:14)
>     at new TDLib (/home/ubuntu/teletipsters/node_modules/tdl-tdlib-ffi/dist/index.js:36:36)
>     at Object.tgClient.initialize (/home/ubuntu/teletipsters/services/tgClient.js:142:13)
>     at main (/home/ubuntu/teletipsters/index.js:15:24)
>     at Object.<anonymous> (/home/ubuntu/teletipsters/index.js:24:1)
>     at Module._compile (internal/modules/cjs/loader.js:816:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
>     at Module.load (internal/modules/cjs/loader.js:685:32)
>     at Function.Module._load (internal/modules/cjs/loader.js:620:12)
>     at Function.Module.runMain (internal/modules/cjs/loader.js:877:12)
>     at internal/main/run_main_module.js:21:11
>   errno: -2,
>   syscall: 'open',
>   code: 'ENOENT',
>   path: 'libtdjson.so' }
> 

Could you give me some help @Bannerets ?

**Comment by CristianBB** [comment]
Solved,
It seems that in linux it is necessary to specify the library path libtdjson.so at the time of TDLib instantiation:

```
    tdlib = new TDLib('/usr/local/lib/libtdjson.so');
    client = new Client(tdlib, {
        apiId: process.env.TELEGRAM_API_ID,
        apiHash: process.env.TELEGRAM_API_HASH
    });

    await client.connectAndLogin();
```

**Comment by Bannerets** [comment]
The `TDLib` constructor accepts a library filename, by default it equals to `libtdjson`. The filename is directly passed to `dlopen` ([ffi-napi/lib/dynamic_library.js#L37-L75](https://github.com/node-ffi-napi/node-ffi-napi/blob/998255a8009cbfca0fc2f2cb7e4fc0a7be30c422/lib/dynamic_library.js#L37-L75)), except for appending the extension ([ffi-napi/lib/library.js#L35-L45](https://github.com/node-ffi-napi/node-ffi-napi/blob/998255a8009cbfca0fc2f2cb7e4fc0a7be30c422/lib/library.js#L35-L45)).
Linux does the rest of the work, so consult the Linux manual: http://man7.org/linux/man-pages/man3/dlopen.3.html.
Also see https://stackoverflow.com/questions/4743233/is-usr-local-lib-searched-for-shared-libraries.

Closing this, since your problem is solved.
