### ISSUE TITLE
Unused methods in ITDLibJSON

### ISSUE THREAD

**Issue by IlyaSemenov** [Bannerets/tdl#72]
The following methods from `ITDLibJSON` (and `IAsyncTDLibJSON`) are never used (called) by tdl client:

```
  setLogFilePath(path: string): number;
  setLogMaxFileSize(maxFileSize: number | string): void;
  setLogVerbosityLevel(verbosity: number): void;
```

Why do they need to be present in the interface?

**Comment by Bannerets** [comment]
Those were used before their deprecation in TDLib.
But since the `TDLib` class can be used independently of the `Client` wrapper, I want to support all the TDLib's [exported functions](https://github.com/tdlib/td/blob/v1.5.0/tdclientjson_export_list). The public interface is also not only for `tdl.Client`.

You can still use them this way:
```js
const { TDLib } = require('tdl-tdlib-ffi')
const tdlib = new TDLib()
tdlib.setLogFilePath('a.txt')
```

For the interface that `Client` accepts, we may create something like `ITDLibJSONMin` without unused methods, I think.
